name: Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ "2.7", "3.0", "3.1", "3.2", jruby ]
        active_support: [ "6.0", "7.0" ]
        exclude:
          - ruby: "3.0"
            active_support: "6.0"
          - ruby: "3.1"
            active_support: "6.0"
          - ruby: "3.2"
            active_support: "6.0"
    name: Ruby ${{ matrix.ruby }} - ActiveSupport ${{ matrix.active_support }}
    env:
      ACTIVE_SUPPORT_VERSION: ${{ matrix.active_support }}
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run Tests
        env:
          RUBYOPT: "-W:deprecated" # Show Ruby's deprecation warnings
        run: |
          bundle exec rake
